# Run our tests against a specific version of astrocyte
before_script:
  - module load astrocyte/2.2.0



stages:
    - check

# This performs validation of the astrocyte_pkg.yml file
astrocyte_check:
  stage: check
  script:
  - astrocyte_cli check "$CI_PROJECT_DIR"
