# Run our tests against a specific version of astrocyte
before_script:
  - module load astrocyte/2.2.0



stages:
    - check
    - deploy

# This performs validation of the astrocyte_pkg.yml file
astrocyte_check:
  stage: check
  script:
  - astrocyte_cli check "$CI_PROJECT_DIR"

pages:
  stage: deploy
  before_script: []
  script:
  - mkdir -p public
  - cp custom-profile-builder.html public/index.html
  artifacts:
    paths:
    - public
  rules:
  - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
