input:
  - /work/bioinformatics/s249154/deconvolution-gpu/1_CH00_000000.tif

output_selection: ozx_1x

iter: 5
background: 0

microscope_profile: ctaslm_v3_50x_ri_1_56

psf_mode: single
psf_model: vectorial

wavelength: 0.610
dz: 0.3

# GPU blind PSF backend. Use "matlab" for the CPU/MATLAB backend.
blind_backend: cupy
cupy_fft_engine: scout
