name: app
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - numpy
  - numba
  - tifffile=2025.5.10
  - zarr=2.18.3
  - numcodecs
  - blosc
  - zstd
  - h5py
  - imagecodecs
  - dask
  - distributed
  - dask-jobqueue
  - scipy
  - psutil
