stages:
    - deploy

pages:
  stage: deploy
  before_script: []
  script:
  - mkdir -p public
  - cp custom-profile-builder.html public/index.html
  artifacts:
    paths:
    - public
  rules:
  - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
